config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create] do
    member do
      get :statistics
      get :commits_frequency
      get :chart_statistics
    end
  end

  get 'widgets/activity_chart'
  get 'widgets/tags_duration_chart'

  root "dashboard#index"

end

app/models/exercise.rb
class Exercise < ActiveRecord::Base
  belongs_to :user

  def children_hashes(i)
    hash = {}
    repo = Git.open(self.user.clone_repo)
    if i == 0
      hash[:sha1] = repo.log(count = 50).last.sha
      hash[:sha2] = commit_hash(repo, Exercise.all[i].name)
    else
      hash[:sha1] = commit_hash(repo, Exercise.all[i - 1].name)
      hash[:sha2] = commit_hash(repo, Exercise.all[i].name)
    end
    hash.values.join(",")
  end

  def commit_hash(repo, tag)
    repo.tag(tag).sha
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  after_save :init_exercises

  validates :name, :repo, presence: true
  has_many :exercises

  def commits(sha1, sha2)
    ActivityService.new(self.clone_repo).commits_between_two_tags(sha1,sha2)
  end

  def chart_statistics
    ActivityService.new(self.clone_repo).commits_hash_per_days
  end

  def tasks
    github = Github.new user: name, repo: repo
    github.repos.tags
  end

  def github_url
    "https://github.com/#{name}/#{repo}.git"
  end

  def clone_repo
    repository = Git.clone(github_url, "#{name}_#{repo}", path: "#{Rails.root}/tmp")
    repository.dir.path
  rescue Git::GitExecuteError
    "#{Rails.root}/tmp/#{name}_#{repo}"
  end

  def repo_events
    Repository.new(clone_repo).events
  end

  def method_statistics
    repo_events.reverse.uniq(&:method_name)
  end

  private

  def init_exercises
    repo = Git.open(clone_repo)
    repo.tags.each_with_index.map do |tag, i|
      exercises.create(name: tag.name,
                       start_date: get_dates(repo, i)[:start_date],
                       end_date: get_dates(repo, i)[:end_date])
    end
  end

  def get_dates(repo, i)
    hash = {}
    if i == 0
      hash[:start_date] = repo.log(count = 50).last.date
      hash[:end_date] = repo.gcommit(repo.tags.first.objectish).date
    else
      hash[:start_date] = repo.gcommit(repo.tags[i-1].objectish).date
      hash[:end_date] = repo.gcommit(repo.tags[i].objectish).date
    end
    hash
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @users = User.all
  end

  def update_activities
  end
end

app/controllers/users_controller.rb
require "analytics"

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  def statistics
    @user = User.find_by(id: params[:id])
    @statistics = @user.method_statistics
    @method_churns = method_churns @user.repo_events
  end

  def commits_frequency
    @user = User.find(params[:id])
    @commits = @user.commits(params[:sha1], params[:sha2])
    render partial: "commits"
  end

  def chart_statistics
    @user = User.find(params[:id])
    @statistics = @user.chart_statistics
    render json: @statistics.to_json
  end

  private

  def user_params
    params.require(:user).permit(:name, :repo)
  end
end

app/controllers/widgets_controller.rb
class WidgetsController < ApplicationController
  after_action :allow_iframes

  def activity_chart
    name, repo = params[:repository].split('/')
    @user = User.find_or_create_by(repo: repo, name: name)
    repository = @user.clone_repo
    @statistics = ActivityService.new(repository).commits_hash_per_days.to_json
  end

  def tags_duration_chart
    name, repo = params[:repository].split('/')
    @user = User.find_or_create_by(repo: repo, name: name)
    @statistics = @user.exercises.map do |exercise|
      { name: exercise.name, duration: exercise.end_date - exercise.start_date }
    end
    @statistics = @statistics.to_json
  end

  private

    def allow_iframes
      response.headers.except! 'X-Frame-Options'
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/dashboard/index.html.erb
<table class="table table-condensed table-striped">
  <th>
    <td class="text-center">Task #1</td>
    <td class="text-center">Task #2</td>
    <td class="text-center">Task #3</td>
    <td class="text-center">Task #4</td>
    <td class="text-center">Refactoring</td>
  </th>
  <% @users.each do |u| %>
    <tr>
      <td>
        <%= link_to u.name, statistics_user_path(u) %>
        <span class="glyphicon glyphicon-signal user-chart" aria-hidden="true" data-id = <%= u.id %>></span>
      </td>
      <% u.exercises.each.with_index  do |e, i| %>
        <td class="success text-center elapsed-time" data-id = "<%= u.id %>" child-tags="<%= e.children_hashes(i) %>"
          <a href=
          <%= "https://github.com/#{u.name}/#{u.repo}/releases/#{e.name}" %>>
           <%= e.name %>
           <%= ((e.end_date - e.start_date)/3600).round(2) %> ч.
         </a>
        </td>
      <% end %>
    </tr>
  <% end %>
</table>

<!-- Modal -->
<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      ...
    </div>
  </div>
</div>

<div style="width: 50%">
  <canvas id="canvas" height="450" width="600"></canvas>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Myapp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class = "container">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">ActivityTracker</a>
        </div>
        <%= link_to "Add user", new_user_path, class: "btn btn-default add-user"%>
      </div>
    </nav>
    <%= yield %>
  </div>

</body>
</html>

app/views/layouts/widgets.html.slim
doctype html
html
  head
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  body
    = yield

app/views/users/_commits.html.erb
<div class = "commits-block">
  <% @commits.each do |c| %>
    <%= link_to c, "https://github.com/" + @user.name + "/" + @user.repo + "/commit/" + c  %> <br>
  <% end %>
</div>

app/views/users/new.html.erb
<h1>Users#new</h1>

<%= form_for @user do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :repo %>
  <%= f.text_field :repo %>
  <%= f.submit %>
<% end %>

app/views/users/statistics.html.erb
<h1>Repository:
  <a href=<%= "https://github.com/#{@user.name}/#{@user.repo}" %>>
    <%= @user.repo %>
  </a>
</h1>
<div class="row">
  <div class="col-sm-12">
    <h3>Methods</h3>
    <table class="table table-striped">
      <th>
        <td class="text-center"><b>Complexity</b></td>
        <td class="text-center"><b>Functional score</b></td>
        <td class="text-center"><b>Length</b></td>
        <td class="text-center"><b>Method Body</b></td>
      </th>
      <% @statistics.each do |stat| %>
        <tr>
          <td><%= stat.method_name %></td>
          <td class="text-center"><%= stat.method_complexity %></td>
          <td class="text-center"><%= stat.method_functional_score %></td>
          <%- if stat.method_length >= 15 %>
            <td class="text-center danger"><%= stat.method_length %></td>
          <%- else %>
            <td class="text-center success"><%= stat.method_length %></td>
          <% end %>
          <td><pre><%= stat.method_body %></pre></td>
        </tr>
      <% end %>
    </table>
  </div>
  <div class="col-sm-4">
    <h3>Most changeable methods</h3>
    <table class="table table-striped">
      <% @method_churns.each do |method| %>
        <tr>
          <td><%= method.first %></td>
          <td><%= method.last %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/widgets/activity_chart.html.slim
h4 Commits frequency
canvas#canvas

script == "window.DATA=#{@statistics}"

coffee:
  $(document).on 'ready page:load', ->
    dates = Object.keys(window.DATA)
    barChartData =
      labels: dates
      datasets: [{
        fillColor: 'rgba(220,220,220,0.5)'
        strokeColor: 'rgba(220,220,220,0.8)'
        highlightFill: 'rgba(220,220,220,0.75)'
        highlightStroke: 'rgba(220,220,220,1)'
        data: dates.map (d)-> window.DATA[d].length - 1
      }]

    ctx = document.querySelector('#canvas').getContext('2d')
    new Chart(ctx).Bar(barChartData, responsive: true)

app/views/widgets/tags_duration_chart.html.slim
h4 Hours per tag
canvas#canvas
script == "window.DATA=#{@statistics}"

coffee:
  $(document).on 'ready page:load', ->
    barChartData =
      labels: window.DATA.map (d)-> d.name
      datasets: [{
        fillColor: 'rgba(220,220,220,0.5)'
        strokeColor: 'rgba(220,220,220,0.8)'
        highlightFill: 'rgba(220,220,220,0.75)'
        highlightStroke: 'rgba(220,220,220,1)'
        data: window.DATA.map (d)-> Math.round(d.duration/360)/10
      }]

    ctx = document.querySelector('#canvas').getContext('2d')
    new Chart(ctx).Bar(barChartData, responsive: true)